grails-app/domain/com/ncmc4/Author.groovy
package com.ncmc4

import groovy.transform.EqualsAndHashCode

@EqualsAndHashCode(includes="name")
class Author {

    static searchable = {
        only = "name"

        root false
    }

    String name

    static mapping = {
        table "grails_author"
        sort "name"
    }

    static constraints = {
        name nullable: false, blank: false
    }

    String getDisplayName()
    {
        return name
    }

    String toString()
    {
        return name
    }

}

grails-app/domain/com/ncmc4/Comment.groovy
package com.ncmc4

import java.beans.Transient
import groovy.transform.EqualsAndHashCode

@EqualsAndHashCode
class Comment {

//    static searchable = {
//        root true
//    }

    String name
    Date creationDate = new Date()
    String comment
    String ipAddress

    SecUser poster

    static belongsTo = [story: Story]

    static constraints = {
        name nullable: true
        ipAddress nullable: true
        poster nullable: true
    }

    static transients = ['title']

    static mapping = {
        table "grails_comment"
        comment type: 'text'
        sort creationDate: "desc"
    }
}

grails-app/views/layouts/authorList.gsp
<g:applyLayout name="newMain" model="[active:'authors']">
    <html>
    <head>
        <title><g:pageTitle title="${title ?: 'Authors'}"/></title>
    </head>
    <body>

    <%
        //sort=name&max=30&order=asc
        if (!params.sort)
            params.sort = "name"
        if (!params.order)
            params.order = "asc"
    %>

    <div class="row">
        <div class="col">
            <ul class="pagination pagination-sm justify-content-center">
                <li class="page-item ${params.authorLetter == null ? 'active' : ''}"><g:link class="page-link" action="index" controller="newStory">All</g:link></li>
                <g:each in="${"abcdefghijklmnopqrstuvwxyz".toCharArray()}">
                    <li class="page-item ${params.authorLetter == it ? 'active' : ''}"><g:link class="page-link" action="letter" controller="newAuthor" id="${it}">${it.toUpperCase()}</g:link></li>
                </g:each>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col mb-2">
            <g:pageProperty name="page.paginate"/>
        </div>
    </div>

    <div class="row">
        <table id="authorList" class="table table-striped" data-rtContainerBreakPoint="539">
            <thead>
            <tr>

                <g:sortableColumn property="name" title="${message(code: 'story.author.label', default: 'Name')}" />

            </tr>
            </thead>
            <tbody>
            <g:each in="${authorInstanceList}" status="i" var="authorInstance">
                <tr>

                    <td><g:link action="show" id="${authorInstance.id}" controller="newAuthor">${fieldValue(bean: authorInstance, field: "name")}</g:link></td>

                </tr>
            </g:each>
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col">
            <g:pageProperty name="page.paginate"/>
        </div>
    </div>

    <content tag="scripts" >
        <g:render template="/newStory/quickLinksScript" />
    </content>

    </body>
    </html>
</g:applyLayout>

grails-app/views/layouts/commentList.gsp
<g:applyLayout name="newMain" model="[active:'comments']" >
    <html>
    <head>
        <title><g:pageTitle title='${title}'/></title>
        <link type="text/css" rel='stylesheet' href="${resource(dir: 'stylesheets', file: 'comment.css')}" />

    </head>
    <body>

    <div class="row">
        <g:pageProperty name="page.title">
            <h1 class="text-center">${title}</h1>
        </g:pageProperty>
    </div>

    <div class="row">
        <div class="col mb-2">
            <g:pageProperty name="page.paginate"/>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <g:each in="${commentInstanceList}" var="comment">
                <g:applyLayout template="/newStory/comment" model="[comment: comment, includeStoryTitle: true]"/>
            </g:each>
        </div>
    </div>

    <div class="row">
        <div class="col mb-2">
            <g:pageProperty name="page.paginate"/>
        </div>
    </div>

        <script>
            <asset:script>
                (function ($, window, document, undefined)
                {
                    'use strict';

                    $(function ()
                    {
                        var thresID = sessionStorage.getItem("lastCommentID");

                        // Auto-Timeout for id 'session'

                        var sessionUpdate = new Date(sessionStorage.getItem("lastCommentIDtime"));
                        if(sessionUpdate) {
                            var anHourAgo = new Date(Date.now() - 1000 * 60 * 60);
                            if(sessionUpdate < anHourAgo) {
                                thresID = null;
                            }
                        }

                        sessionStorage.setItem("lastCommentIDtime",new Date().toJSON());

                        if(! thresID)
                        {
                            thresID = localStorage.getItem("lastCommentID")
                            if(! thresID)
                                thresID = 0;

                            sessionStorage.setItem("lastCommentID",thresID);
                        }

                        var highID = thresID;

                        $(".newCommentStar").each(function(index,elem) {
                            var itemID = $(elem).data('id');
                            if(itemID > thresID)
                                $(elem).removeClass("d-none");
                            if(itemID > highID)
                                highID = itemID;
                        });

                        localStorage.setItem("lastCommentID",highID);
                    });

                    <sec:ifAllGranted roles="ROLE_BASIC">
                        $(function ()
                        {
                            $(".deleteCommentButton").click(
                                    function() {

                                        var id = $(this).data('id');
                                        var data = {'id': id};

                                        $.ajax({
                                            url: "${createLink(action: 'deleteComment', controller: 'newComment')}",
                                            type: 'GET',
                                            data: data,
                                            success: function(response) {
                                                if (response == 'empty') {
                                                } else {
                                                    var divId = "#comment-" + id;

                                                    $(divId).hide('slow', function(){ $(divId).remove(); });
                                                }
                                            }
                                        });
                                    }
                            );
                        });
                    </sec:ifAllGranted>
                })(jQuery, window, document);
            </asset:script>
        </script>
    </body>
    </html>

</g:applyLayout>

grails-app/views/layouts/storyList.gsp
<g:applyLayout name="newMain" model="[active:'stories']">
    <html>
    <head>
        <title><g:pageTitle title='${title ?: 'Stories'}'/></title>

        <link href="${resource(dir: 'stylesheets', file: 'newstories.css')}" rel="stylesheet">
    </head>
    <body>

    <div class="row">
        <div class="col">
            <g:pageProperty name="page.headline"/>
        </div>
    </div>

    <div class="row">

        <%
            //sort=name&max=30&order=asc
            if (!params.sort)
                params.sort = "publishDate"
            if (!params.order)
                params.order = "desc"
        %>
    </div>

    <g:if test="${showLetterLinks}">
        <div class="row">
            <div class="col">
                <ul class="pagination pagination-sm justify-content-center d-flex flex-wrap">
                    <li class="page-item ${params.storyLetter == null ? 'active' : ''}"><g:link class="page-link" action="index" controller="newStory">All</g:link></li>
                    <g:each in="${"abcdefghijklmnopqrstuvwxyz".toCharArray()}">
                        <li class="page-item ${params.storyLetter == it ? 'active' : ''}"><g:link class="page-link" action="letter" controller="newStory" id="${it}">${it.toUpperCase()}</g:link></li>
                    </g:each>
                </ul>
            </div>
        </div>
    </g:if>

    <div class="row">
        <div class="col">
            <g:pageProperty name="page.title" ><h1 class="center-block text-center">${title}</h1></g:pageProperty>
        </div>
    </div>

    <div class="d-flex flex-column flex-sm-row justify-content-center justify-content-sm-between">
        <div class="mb-2 d-flex justify-content-center">
            <g:render template="/templates/categorySelector" model="[instance: '1']"/>
        </div>
        <div class="mb-2">
            <g:pageProperty name="page.paginate"/>
        </div>
        <sec:ifAllGranted roles="ROLE_SUPER_ADMIN">
            <div class="mb-2 d-flex justify-content-center">
                <g:render template="/newStory/storyAdminControls" />
            </div>
        </sec:ifAllGranted>
    </div>

    <div class="row">
        <g:render template="/newStory/storyTable" model="[storyInstanceList: storyInstanceList]" />
    </div>

    <div class="d-flex flex-column flex-sm-row justify-content-center justify-content-sm-between">
        <div class="mb-2 d-flex justify-content-center">
            <g:render template="/templates/categorySelector" model="[instance: '2']"/>
        </div>
        <div class="mb-2">
            <g:pageProperty name="page.paginate"/>
        </div>
    </div>

    <g:pageProperty name="page.dialogs"/>

    </body>
</html>
</g:applyLayout>