grails-app/controllers/com/ncmc4/SystemStatsController.groovy
package com.ncmc4

import grails.plugin.springsecurity.annotation.Secured

@Secured(value=["hasRole('ROLE_SUPER_ADMIN')"])
class SystemStatsController {

    SystemAdminService systemAdminService
    StoryService storyService
    CommentService commentService
    TagService tagService
    HeaderService headerService
    def elasticSearchService


    def index() {

        //render view:"index"
        def serverInfo = session.servletContext.getServerInfo()
        
        Runtime runtime = Runtime.getRuntime();

        long maxMemory = runtime.maxMemory();
        long allocatedMemory = runtime.totalMemory();
        long freeMemory = runtime.freeMemory();

        render view:"index", model:[freeMemory: freeMemory, allocatedMemory: allocatedMemory, maxMemory: maxMemory, totalFreeMemory: freeMemory + (maxMemory - allocatedMemory), serverInfo: serverInfo]
    }

    def resetEtags() {
        headerService.resetEtags()

        flash.message = "Etags Reset"

        index()
    }

    def resetCommentCache() {
        commentService.resetCache()

        flash.message = "Updated comment cache"

        index()
    }

    def resetPatreon() {
        systemAdminService.resetPatreon()

        flash.message = "Patreon role reset"

        index()
    }

    def fixUserCounts() {
        systemAdminService.fixUserCounts()

        flash.message = "Queued fix of user counts"

        index()
    }

    def resetSeriesLinks() {
        systemAdminService.resetSeriesLinks()

        flash.message = "Queued fix series"

        index()
    }

    def fixStoryCommentCounts() {
        systemAdminService.fixCommentCounts(true)

        flash.message = "Queued fix of story comment counts"

        index()
    }

    def resetTagCache() {
        tagService.resetCache()

        flash.message = "Reset tag cache"

        index()
    }

    def reindexSearch() {
        elasticSearchService.index()

        flash.message = "Search index recreated"

        index()
    }

    def garbageCollect() {
        System.gc()

        flash.message = "Garbage Collection Performed"

        index()
    }
}

grails-app/views/systemStats/index.gsp
<g:applyLayout name="newMain" model="[active:'admin']">
    <html>
    <head>
        <meta name="robots" content="noindex">

        <title><g:pageTitle title='System Stats'/></title>

        %{--<asset:stylesheet href="secuser.css"/>--}%
    </head>
    <body>

    <div class="row">
        <div class="spacer20"></div>
    </div>

    <div class="row">
        <div class="col">
            <p>Free Memory: ${(int) (freeMemory / (1024 * 1024))} mbs<br/>
            Allocated Memory: ${(int) (allocatedMemory / (1024 * 1024))} mbs<br/>
            Total Free Memory: ${(int) (totalFreeMemory / (1024 * 1024))} mbs<br/>
            Server Info: ${serverInfo}</p>
        </div>
    </div>
    <div class="row">
        <div class="spacer20"></div>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="d-flex flex-wrap justify-content-around">
                <g:link class="btn btn-info" controller="systemStats" action="resetEtags">Reset Etags</g:link>
                <g:link class="btn btn-info" controller="systemStats" action="resetPatreon">Reset Patreon Role</g:link>
                <g:link class="btn btn-info" controller="systemStats" action="resetCommentCache">Reset Comment Cache</g:link>
                <g:link class="btn btn-info" controller="systemStats" action="fixUserCounts">Fix User Counts</g:link>
                <g:link class="btn btn-info" controller="systemStats" action="resetSeriesLinks">Reset Series Links & Categories</g:link>
                <g:link class="btn btn-info" controller="systemStats" action="fixStoryCommentCounts">Fix Story Comment Counts</g:link>
                <g:link class="btn btn-info" controller="systemStats" action="resetTagCache">Reset Tag Cache</g:link>
                <g:link class="btn btn-info" controller="systemStats" action="reindexSearch">Reindex Search</g:link>
                <g:link class="btn btn-info" controller="systemStats" action="garbageCollect">Garbage Collect</g:link>
            </div>
    </div>

    <div class="row">
        <div class="spacer20"></div>
    </div>

    </body>
    </html>
</g:applyLayout>